# NUMPY

import 

In [2]:
import numpy as np

NUMPY Array

In [3]:
list=[1,2,3]
np.array(list)

array([1, 2, 3])

Arange function

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

creating array of 0's 

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

linspace function- it generate a series of numbers in a range with equal difference

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

creating identity matrix using eye function

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

random function generate random number

In [17]:
np.random.rand(5)

array([0.75859043, 0.92015252, 0.22914794, 0.30411049, 0.49718947])

randint gives random integer over a given range

In [18]:
np.random.randint(1,100)

16

In [20]:
np.random.randint(1,100,10)

array([71, 52, 78, 37, 59,  9, 26, 85, 67, 63])

reshape of array

In [22]:
arr=np.arange(0,4)
arr.reshape(2,2)

array([[0, 1],
       [2, 3]])

maximum number in a array

In [23]:
arr.max()

3

minimum number in a array

In [25]:
arr.min()

0

In [26]:
arr.dtype

dtype('int32')

In [27]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

Trigonometry function in numpy

In [29]:
np.sin(arr)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [32]:
np.log(arr)

C:\Users\wave technology\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [33]:
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])